pipeline {
     agent {
                dockerfile {
                    // Assumes there's a Dockerfile in ./devcontainer
                    // This will build the Docker image based on that Dockerfile
                    // and use it as the build environment
                    filename "Dockerfile"
                    dir ".devcontainer"
                    args "-v /var/run/docker.sock:/var/run/docker.sock "
                }
            }
    
    stages {
        stage('Build') {
           
            steps {
                // Your build commands go here
                // Example:
                script {
                    sh '''
                    cmake --preset release_build
                    cd build/release && cmake --build . -j ${nproc}
                    '''
                }
            }
        }
    }
    post {
        always {
            // Post-build actions like cleaning up, notifications, etc.
            echo 'Build process completed.'
        }
    }
}
